import PDFDocument from "pdfkit";
import { parseDataUrl } from "@/app/lib/groq";
import {
  badgeHeight,
  badgeWidth,
  categoryColor,
  drawAccentBar,
  drawBadge,
  drawBadgeRight,
  drawCard,
  EVIDENCE_STATUS_COLOR,
  EVIDENCE_STATUS_LABEL,
  INK,
  INK_SOFT,
  SEVERITY_COLOR,
  SEVERITY_LABEL,
} from "@/app/lib/pdfStyle";
import { formatText, titleCase } from "@/app/lib/textFormat";
import type { DefectSignature, EvidenceCheckItem, RoomWalkthroughElement, RoomWalkthroughResult } from "@/app/lib/types";

// Starts a fresh page if the next block won't fit above the bottom margin.
function ensureSpace(doc: PDFKit.PDFDocument, y: number, needed: number): number {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (y + needed > bottom) {
    doc.addPage();
    return doc.page.margins.top;
  }
  return y;
}

function defectCardText(d: DefectSignature) {
  return {
    description: formatText(d.description),
    meta: `${formatText(d.region)} · ${Math.round(d.confidence * 100)}% confidence · ${
      d.recommended_action === "flag_for_review" ? "Flag for review" : "Pass"
    }`,
  };
}

// Measures the exact height drawDefectCard will use, so the caller can
// paginate BEFORE drawing anything — pdfkit can't retroactively move ink
// that already landed on the wrong page.
function measureDefectCardHeight(doc: PDFKit.PDFDocument, d: DefectSignature, width: number): number {
  const pad = 10;
  const contentWidth = width - pad * 2;
  const { description, meta } = defectCardText(d);

  doc.font("Helvetica").fontSize(10);
  const descHeight = doc.heightOfString(description, { width: contentWidth });
  doc.font("Helvetica").fontSize(9);
  const metaHeight = doc.heightOfString(meta, { width: contentWidth });
  const sigHeight = 13;
  const gap = 5;
  return pad * 2 + sigHeight + gap + descHeight + gap + metaHeight;
}

function drawDefectCard(doc: PDFKit.PDFDocument, d: DefectSignature, x: number, y: number, width: number): number {
  const pad = 10;
  const contentWidth = width - pad * 2;
  const { description, meta } = defectCardText(d);

  doc.font("Helvetica").fontSize(10);
  const descHeight = doc.heightOfString(description, { width: contentWidth });
  doc.font("Helvetica").fontSize(9);
  const metaHeight = doc.heightOfString(meta, { width: contentWidth });
  const sigHeight = 13;
  const gap = 5;
  const cardHeight = pad * 2 + sigHeight + gap + descHeight + gap + metaHeight;

  drawCard(doc, x, y, width, cardHeight);

  const contentX = x + pad;
  let cy = y + pad;

  const sevText = SEVERITY_LABEL[d.severity];
  const bw = badgeWidth(doc, sevText, 8.5);
  doc
    .fillColor(INK)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text(titleCase(d.signature), contentX, cy, { width: contentWidth - bw - 8, lineBreak: false });
  drawBadge(doc, sevText, contentX + contentWidth - bw, cy - 1, SEVERITY_COLOR[d.severity], 8.5);
  cy += sigHeight + gap;

  doc.fillColor(INK).font("Helvetica").fontSize(10).text(description, contentX, cy, { width: contentWidth });
  cy += descHeight + gap;

  doc.fillColor(INK_SOFT).font("Helvetica").fontSize(9).text(meta, contentX, cy, { width: contentWidth });

  return y + cardHeight;
}

// Built with pdfkit directly (the engine @react-pdf/renderer itself wraps),
// avoiding a React-reconciler element-identity conflict that @react-pdf/renderer
// hits when its components are compiled through Next's own bundled React copy.
export function renderEvidenceReportPdf(images: { base64: string; analysis: EvidenceCheckItem }[]): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const left = doc.page.margins.left;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const right = left + pageWidth;

  let y = doc.page.margins.top;
  doc.rect(left, y, 4, 30).fill(EVIDENCE_STATUS_COLOR.clean.fg);
  doc
    .fillColor(INK)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text("Evidence Consistency — Full Report", left + 14, y, { width: pageWidth - 14 });
  doc
    .fillColor(INK_SOFT)
    .font("Helvetica")
    .fontSize(9.5)
    .text(`${images.length} photo${images.length > 1 ? "s" : ""} · generated by PTP360 Second-Pass QA`, left + 14, doc.y + 2, {
      width: pageWidth - 14,
    });
  y = Math.max(doc.y, y + 30);

  images.forEach((image, i) => {
    if (i > 0) {
      doc.addPage();
      y = doc.page.margins.top;
    } else {
      y += 20;
    }

    const item = image.analysis;

    try {
      const { data } = parseDataUrl(image.base64);
      doc.image(Buffer.from(data, "base64"), left, y, { fit: [pageWidth, 300], align: "center" });
      y += 310;
    } catch {
      doc.fillColor(INK_SOFT).font("Helvetica").fontSize(10).text("(image could not be embedded)", left, y);
      y = doc.y + 10;
    }

    if (item.error) {
      doc.fillColor(INK).font("Helvetica-Bold").fontSize(12).text("This photo couldn't be analyzed.", left, y);
      return;
    }

    const analysis = item.analysis;

    doc
      .fillColor(INK_SOFT)
      .font("Helvetica")
      .fontSize(10)
      .text(titleCase(analysis.detected_location) || "Location unclear", left, y, { width: pageWidth - 140, lineBreak: false });
    drawBadgeRight(doc, EVIDENCE_STATUS_LABEL[analysis.overall.status], right, y - 2, EVIDENCE_STATUS_COLOR[analysis.overall.status], 9.5);
    y += badgeHeight(9.5) + 8;

    if (analysis.defect_signatures.length === 0) {
      doc.fillColor(INK_SOFT).font("Helvetica-Oblique").fontSize(11).text("Nothing concerning was visible.", left, y);
      y = doc.y + 8;
    } else {
      for (const d of analysis.defect_signatures) {
        y = ensureSpace(doc, y, measureDefectCardHeight(doc, d, pageWidth));
        y = drawDefectCard(doc, d, left, y, pageWidth) + 10;
      }
    }

    y = ensureSpace(doc, y, 30);
    drawAccentBar(doc, left, y, 26, 2.5);
    y += 10;

    const summary = formatText(analysis.overall.summary);
    doc.font("Helvetica").fontSize(10);
    const summaryWidth = pageWidth - 110;
    const summaryHeight = doc.heightOfString(summary, { width: summaryWidth });
    doc.fillColor(INK).text(summary, left, y, { width: summaryWidth });
    doc
      .fillColor(INK_SOFT)
      .font("Helvetica-Bold")
      .fontSize(9.5)
      .text(`Risk ${analysis.overall.risk_score}/100`, right - 90, y, { width: 90, align: "right" });
    y += Math.max(summaryHeight, 12);
  });

  doc.end();
  return done;
}

function elementCardText(element: RoomWalkthroughElement) {
  return {
    conditionText: formatText(element.condition_observed),
    seenText: `Seen in photo${element.seen_in_images.length > 1 ? "s" : ""} ${element.seen_in_images.join(", ")}`,
    recommendText: element.recommended_check ? formatText(element.recommended_check) : null,
  };
}

function measureElementCardHeight(doc: PDFKit.PDFDocument, element: RoomWalkthroughElement, width: number): number {
  const pad = 10;
  const contentWidth = width - pad * 2;
  const { conditionText, seenText, recommendText } = elementCardText(element);

  doc.font("Helvetica").fontSize(10.5);
  const conditionHeight = doc.heightOfString(conditionText, { width: contentWidth });
  doc.font("Helvetica").fontSize(9);
  const seenHeight = doc.heightOfString(seenText, { width: contentWidth });
  const recommendHeight = recommendText ? doc.heightOfString(`Recommend: ${recommendText}`, { width: contentWidth }) : 0;

  const titleRowHeight = 14;
  const severityRowHeight = element.defect_signatures.length > 0 ? badgeHeight(8.5) + 6 : 0;
  const noConcernHeight = element.defect_signatures.length === 0 ? 12 : 0;
  const gap = 5;

  return (
    pad * 2 +
    titleRowHeight +
    gap +
    seenHeight +
    gap +
    conditionHeight +
    gap +
    severityRowHeight +
    noConcernHeight +
    (recommendText ? gap + recommendHeight : 0)
  );
}

// Measures the exact height first (measureElementCardHeight) so the caller
// can paginate before drawing — pdfkit can't retroactively move ink that
// already landed on the wrong page.
function drawElementCard(
  doc: PDFKit.PDFDocument,
  element: RoomWalkthroughElement,
  x: number,
  y: number,
  width: number
): number {
  const pad = 10;
  const contentWidth = width - pad * 2;
  const { conditionText, seenText, recommendText } = elementCardText(element);

  doc.font("Helvetica").fontSize(10.5);
  const conditionHeight = doc.heightOfString(conditionText, { width: contentWidth });
  doc.font("Helvetica").fontSize(9);
  const seenHeight = doc.heightOfString(seenText, { width: contentWidth });
  const recommendHeight = recommendText ? doc.heightOfString(`Recommend: ${recommendText}`, { width: contentWidth }) : 0;

  const titleRowHeight = 14;
  const severityRowHeight = element.defect_signatures.length > 0 ? badgeHeight(8.5) + 6 : 0;
  const noConcernHeight = element.defect_signatures.length === 0 ? 12 : 0;
  const gap = 5;

  const cardHeight =
    pad * 2 +
    titleRowHeight +
    gap +
    seenHeight +
    gap +
    conditionHeight +
    gap +
    severityRowHeight +
    noConcernHeight +
    (recommendText ? gap + recommendHeight : 0);

  drawCard(doc, x, y, width, cardHeight);

  const contentX = x + pad;
  let cy = y + pad;

  const catText = element.category;
  const bw = badgeWidth(doc, catText, 8.5);
  doc
    .fillColor(INK)
    .font("Helvetica-Bold")
    .fontSize(12)
    .text(titleCase(element.element), contentX, cy, { width: contentWidth - bw - 8, lineBreak: false });
  drawBadge(doc, catText, contentX + contentWidth - bw, cy - 1, categoryColor(element.category), 8.5);
  cy += titleRowHeight + gap;

  doc.fillColor(INK_SOFT).font("Helvetica").fontSize(9).text(seenText, contentX, cy, { width: contentWidth });
  cy += seenHeight + gap;

  doc.fillColor(INK).font("Helvetica").fontSize(10.5).text(conditionText, contentX, cy, { width: contentWidth });
  cy += conditionHeight + gap;

  if (element.defect_signatures.length > 0) {
    let bx = contentX;
    for (const d of element.defect_signatures) {
      const label = `${titleCase(d.signature)} · ${SEVERITY_LABEL[d.severity]} · ${Math.round(d.confidence * 100)}%`;
      const w = drawBadge(doc, label, bx, cy, SEVERITY_COLOR[d.severity], 8.5);
      bx += w + 6;
    }
    cy += severityRowHeight;
  } else {
    doc.fillColor(INK_SOFT).font("Helvetica-Oblique").fontSize(9.5).text("No concerns visible", contentX, cy, { width: contentWidth });
    cy += noConcernHeight;
  }

  if (recommendText) {
    cy += gap;
    doc
      .fillColor(INK_SOFT)
      .font("Helvetica")
      .fontSize(9)
      .text(`Recommend: ${recommendText}`, contentX, cy, { width: contentWidth });
  }

  return y + cardHeight;
}

// Room Walkthrough mode — same toolchain/route as Single Photo mode above,
// just a different payload shape: the room's photos up top, then each
// detected element written out below (no per-image pairing, since one
// element can cite several images at once).
export function renderRoomWalkthroughReportPdf(images: string[], result: RoomWalkthroughResult): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const left = doc.page.margins.left;
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  let y = doc.page.margins.top;
  doc.rect(left, y, 4, 30).fill(EVIDENCE_STATUS_COLOR.clean.fg);
  doc
    .fillColor(INK)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text(`Room Walkthrough — ${titleCase(result.room)}`, left + 14, y, { width: pageWidth - 14 });
  doc
    .fillColor(INK_SOFT)
    .font("Helvetica")
    .fontSize(10)
    .text(formatText(result.overall_summary), left + 14, doc.y + 2, { width: pageWidth - 14 });
  y = Math.max(doc.y, y + 30) + 16;

  const thumbWidth = Math.min(110, (pageWidth - 8 * (images.length - 1)) / Math.max(images.length, 1));
  images.forEach((base64, i) => {
    try {
      const { data } = parseDataUrl(base64);
      doc.image(Buffer.from(data, "base64"), left + i * (thumbWidth + 8), y, {
        width: thumbWidth,
        height: thumbWidth,
      });
    } catch {
      // skip an image that couldn't be embedded rather than failing the whole PDF
    }
  });
  y += thumbWidth + 20;

  result.detected_elements.forEach((element) => {
    y = ensureSpace(doc, y, measureElementCardHeight(doc, element, pageWidth));
    y = drawElementCard(doc, element, left, y, pageWidth) + 12;
  });

  doc.end();
  return done;
}
